version: '3.8'


services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./src/mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-5.2.4
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: 1234
    ports:
       - '10051:10051'
    restart: unless-stopped
    depends_on:
      - mysql-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-5.2.4
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: mysql-server
      DB_SERVER_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: 1234
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      PHP_TZ: Europe/Kiev
    ports:
      - '80:8080'
      - '443:8443'
    restart: always
    depends_on:
      - zabbix-server
      - mysql-server

  agent:
    # Image tag (replace with yours)
    image: zabbix/zabbix-agent:ubuntu-5.2.4
    environment:
      # Zabbix Hostname (replace with yours)
      # Set as DNS name on Zabbix server host configuration screen to make checks of Zabbix server itself
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "10050:10050"
    restart: unless-stopped
    depends_on:
      - mysql-server
      - zabbix-server